[package]
name = "mfoa-hash-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
sha2 = "0.10"
hex = "0.4"

[profile.release]
opt-level = "z"
lto = true

